version: "3"
services:
  client:
    container_name: client
    image: client
    build:
      context:
        account
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  server:
    container_name: server
    image: server
    build:
      context:
        server
      dockerfile: Dockerfile
    ports:
      - "8083:8083"